export const PHOTOS_PAGE_LOADING = 'PHOTOS_LOADING';
export const PHOTOS_PAGE_LOADED = 'PHOTOS_LOADED';
export const PHOTOS_PAGE_FAILED_TO_LOAD = 'PHOTOS_FAILED_TO_LOAD';

export const FETCHING_PHOTOS = 'FETCHING_PHOTOS';
export const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
export const FETCH_PHOTOS_FAIL = 'FETCH_PHOTOS_FAIL';

export const PHOTO_SELECTED = 'PHOTO_SELECTED';
export const PHOTO_UNSELECTED = 'PHOTO_UNSELECTED';
